## Config file for automatic testing at travis-ci.org

language: python

services:
  - postgresql

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.7
      env: TOXENV=py37-django111
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.7
      env: TOXENV=py37-django20
      dist: xenial
      sudo: true
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7
      env: TOXENV=py37-django21
      dist: xenial
      sudo: true
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
      dist: xenial
      sudo: true

before_script:
  - psql -c 'create database djangowebix_test;' -U postgres

install:
  - pip install coverage mock flake8 tox codecov

script:
  - tox -e $TOXENV

after_success:
  - codecov -e TOXENV
