# Generated by Django 3.0.7 on 2020-08-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webixadminmenu',
            options={'verbose_name': 'Webix Admin Menu', 'verbose_name_plural': 'Webix Admin Menu'},
        ),
    ]
