#from .tests_base import TestFakeLogin
#from .tests_urls import TestUrlsCalls
#from .tests_permissions import TestPermissionsCalls
#from .tests_detailview import TestDetailViewCalls
#from .tests_listview import TestListViewCalls
#from .tests_createview import TestCreateViewCalls
#from .tests_deleteview import TestDeleteViewCalls
#from .tests_updateview import TestUpdateViewCalls
#from .tests_adminwebix import TestAdminWebixCalls
