# Generated by Django 3.2.16 on 2022-11-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebixFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Insert date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('filter', models.JSONField(blank=True, null=True, verbose_name='Filter')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', max_length=32, verbose_name='Visiblity')),
                ('shared_edit_group', models.BooleanField(blank=True, verbose_name='Shared edit group')),
                ('assignees_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Assignees groups')),
                ('insert_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Insert user')),
            ],
            options={
                'verbose_name': 'Webix Filter',
                'verbose_name_plural': 'Webix Filters',
            },
        ),
    ]
