# Generated by Django 2.2.9 on 2020-03-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterquerybuilder',
            old_name='fitler',
            new_name='filter',
        ),
    ]
