# Generated by Django 4.2.2 on 2023-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwfilter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webixfilter',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', max_length=32, verbose_name='Visibility'),
        ),
    ]
