# Generated by Django 2.2.9 on 2020-03-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0002_auto_20200317_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterquerybuilder',
            options={'verbose_name': 'Filter Query Builder', 'verbose_name_plural': 'Filters Query Builder'},
        ),
    ]
