# Generated by Django 5.1.2 on 2025-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dwfilter", "0002_alter_webixfilter_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="webixfilter",
            name="temporary",
            field=models.BooleanField(blank=True, default=False, verbose_name="Temporary filter"),
        ),
    ]
