# Generated by Django 3.0.5 on 2020-05-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0003_auto_20200320_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterQueryBuilder',
            new_name='WebixFilter',
        ),
        migrations.AlterModelOptions(
            name='webixfilter',
            options={'verbose_name': 'Webix Filter', 'verbose_name_plural': 'Webix Filters'},
        ),
    ]
