# Generated by Django 3.1 on 2020-09-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0001_initial'),
        ('django_webix_filter', '0004_auto_20200507_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='webixfilter',
            name='assignees_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Gruppi assegnati'),
        ),
        migrations.AddField(
            model_name='webixfilter',
            name='insert_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webixfilter',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Filto privato'),
        ),
    ]
