# Generated by Django 3.1.1 on 2020-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0005_auto_20200901_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webixfilter',
            name='private',
        ),
        migrations.AddField(
            model_name='webixfilter',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pubblico'), ('private', 'Privato'), ('restricted', 'Ristretto ai gruppi selezionati')], default='public', max_length=32, verbose_name='Visibilità'),
        ),
    ]
