# Generated by Django 3.1.1 on 2020-09-02 06:53

import django
from django.db import migrations, models
import django_webix_filter.managers

from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0006_auto_20200901_1651'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='webixfilter',
            managers=[
                ('objects', django_webix_filter.managers.WebixFilterManager()),
            ],
        ),
        migrations.AlterField(
            model_name='webixfilter',
            name='filter',
            field=JSONField(blank=True, null=True),
        ),
    ]
