# Generated by Django 3.2.1 on 2021-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_filter', '0007_auto_20200902_0853'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='webixfilter',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='webixfilter',
            name='shared_edit_group',
            field=models.BooleanField(blank=True, default=False, verbose_name='Modifica abilitata al gruppo'),
            preserve_default=False,
        ),
    ]
