# Generated by Django 3.2 on 2022-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, verbose_name='Description')),
                ('command_name', models.CharField(choices=[('app_cache', 'app_cache'), ('crea_excel_operatori_patentini', 'crea_excel_operatori_patentini'), ('crea_excel_appezzamenti', 'crea_excel_appezzamenti'), ('crea_excel_attrezzature_scadenze', 'crea_excel_attrezzature_scadenze'), ('crea_excel_concimazioni', 'crea_excel_concimazioni'), ('crea_excel_trattamenti', 'crea_excel_trattamenti'), ('crea_excel_qdc_conformita', 'crea_excel_qdc_conformita'), ('crea_pdf_qdc', 'crea_pdf_qdc'), ('crea_zip_pdf_cantina', 'crea_zip_pdf_cantina'), ('ricalcola_qdc_restrizioni_cambiate', 'ricalcola_qdc_restrizioni_cambiate')], max_length=64, verbose_name='Command name')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parameters')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Insert date')),
                ('last_execution_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Execution')),
                ('last_execution_state', models.CharField(choices=[('started', 'Started'), ('error', 'Error'), ('finished', 'Finished'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
            ],
            options={
                'verbose_name': 'Command execution',
                'verbose_name_plural': 'Commands executions',
            },
        ),
    ]
