# Generated by Django 3.2 on 2022-03-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_commands_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
    ]
