# Generated by Django 3.2 on 2022-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_commands_manager', '0002_commandexecution_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandexecution',
            name='command_name',
            field=models.CharField(choices=[('app_cache', 'app_cache'), ('crea_excel_operatori_patentini', 'crea_excel_operatori_patentini'), ('crea_excel_appezzamenti', 'crea_excel_appezzamenti'), ('crea_excel_attrezzature_scadenze', 'crea_excel_attrezzature_scadenze'), ('crea_excel_concimazioni', 'crea_excel_concimazioni'), ('crea_excel_trattamenti', 'crea_excel_trattamenti'), ('crea_excel_qdc_conformita', 'crea_excel_qdc_conformita'), ('crea_pdf_qdc', 'crea_pdf_qdc'), ('crea_zip_pdf_cantina', 'crea_zip_pdf_cantina'), ('ricalcola_qdc_restrizioni_cambiate', 'ricalcola_qdc_restrizioni_cambiate'), ('set_groups_layers_webgis', 'set_groups_layers_webgis'), ('set_groups_fieldsets_webgis', 'set_groups_fieldsets_webgis')], max_length=64, verbose_name='Command name'),
        ),
    ]
