# Generated by Django 5.1 on 2024-08-26 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dwextra_fields", "0002_alter_modelfield_field_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="modelfieldvalue",
            new_name="dwextra_fie_content_943412_idx",
            old_fields=("content_type", "object_id"),
        ),
        migrations.RenameIndex(
            model_name="modelfieldvalue",
            new_name="dwextra_fie_content_caec7b_idx",
            old_fields=("content_type", "object_id", "model_field"),
        ),
    ]
