# Generated by Django 5.1 on 2024-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dwextra_fields", "0002_alter_modelfield_field_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="modelfieldvalue",
            index=models.Index(fields=["content_type", "object_id"], name="dwextra_fie_content_943412_idx"),
        ),
        migrations.AddIndex(
            model_name="modelfieldvalue",
            index=models.Index(
                fields=["content_type", "object_id", "model_field"], name="dwextra_fie_content_caec7b_idx"
            ),
        ),
    ]
