# Generated by Django 2.2.10 on 2020-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('tipologia', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=32, verbose_name='Tipologia tutorial')),
                ('target', models.CharField(choices=[('iframe', 'Modale con iframe'), ('_self', 'Stessa finestra'), ('_blank', 'Nuovo tab')], default='_self', max_length=32, verbose_name='Tipologia di apertura del file')),
                ('visibile_dal', models.DateField(blank=True, null=True, verbose_name='Visibile dal')),
                ('visibile_al', models.DateField(blank=True, null=True, verbose_name='Visibile al')),
            ],
            options={
                'verbose_name': 'Elemento tutorial',
                'verbose_name_plural': 'Elementi tutorial',
            },
        ),
    ]
