# Generated by Django 2.2.10 on 2020-03-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Area tutorial',
                'verbose_name_plural': 'Aree tutorial',
            },
        ),
        migrations.AddField(
            model_name='tutorialitem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_webix_tutorial.TutorialArea'),
        ),
    ]
