# Generated by Django 3.2.3 on 2021-05-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_webix_tutorial', '0002_auto_20200330_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialarea',
            options={'ordering': ['nome'], 'verbose_name': 'Area tutorial', 'verbose_name_plural': 'Aree tutorial'},
        ),
        migrations.AlterModelOptions(
            name='tutorialitem',
            options={'ordering': ['nome'], 'verbose_name': 'Elemento tutorial', 'verbose_name_plural': 'Elementi tutorial'},
        ),
    ]
