# Generated by Django 4.1.5 on 2023-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwsender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetypology',
            name='read_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Read required'),
        ),
    ]
