# Generated by Django 4.1.5 on 2023-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwsender', '0002_messagetypology_read_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTypologiesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_typologies', models.CharField(max_length=255, unique=True, verbose_name='Group typologies')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification data')),
                ('message_typologies', models.ManyToManyField(to='dwsender.messagetypology', verbose_name='Message typologies')),
            ],
            options={
                'verbose_name': 'Message typologies group',
                'verbose_name_plural': 'Message typologies groups',
            },
        ),
    ]
