# Generated by Django 2.2.9 on 2020-12-16 10:40

from django.conf import settings
from django.db import migrations, models

CONF = getattr(settings, "WEBIX_SENDER", None)


class Migration(migrations.Migration):
    dependencies = [
        ('django_webix_sender', '0003_auto_20201125_1257'),
    ]

    operations = []

    if any(_recipients['model'] == 'django_webix_sender.Customer' for _recipients in CONF['recipients']):
        operations.append(migrations.AddField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ))

    if any(_recipients['model'] == 'django_webix_sender.ExternalSubject' for _recipients in CONF['recipients']):
        operations.append(migrations.AddField(
            model_name='externalsubject',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ))
