# Generated by Django 4.1.5 on 2023-03-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwsender', '0003_messagetypologiesgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesent',
            name='typology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dwsender.messagetypology', verbose_name='Typology'),
        ),
    ]
