# Generated by Django 4.1.5 on 2023-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwsender', '0004_alter_messagesent_typology'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetypologiesgroup',
            name='icon',
            field=models.CharField(default=None, help_text='ex. "fas fa-inbox-in"', max_length=255, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
