# Generated by Django 4.1.7 on 2023-05-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwsender', '0005_messagetypologiesgroup_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesent',
            name='read_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Read required'),
        ),
    ]
