# Generated by Django 3.1.5 on 2021-01-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_webix_sender', '0006_auto_20210113_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecipient',
            name='read',
        ),
        migrations.CreateModel(
            name='MessageUserRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_webix_sender.messagesent', verbose_name='Message sent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification data')),
            ],
            options={
                'verbose_name': 'Readed message',
                'verbose_name_plural': 'Readed messages',
                'unique_together': {('message_sent', 'user')},
            },
        ),
    ]
