# Generated by Django 3.2.16 on 2022-11-14 14:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebixAdminMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Node name')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon')),
                ('url', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Web link')),
                ('enabled', models.BooleanField(blank=True, default=True, verbose_name='Enabled')),
                ('active_all', models.BooleanField(blank=True, default=True, verbose_name='Active for all')),
                ('prefix', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Prefix')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Enabled groups')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dwadmin.webixadminmenu', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Webix Admin Menu',
                'verbose_name_plural': 'Webix Admin Menu',
            },
        ),
    ]
