# Generated by Django 4.2.3 on 2023-07-27 16:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dwadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='webixadminmenu',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
