# Generated by Django 3.0.7 on 2020-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webix', '0002_auto_20200810_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='webixadminmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icona'),
        ),
    ]
