# Generated by Django 4.2.6 on 2024-01-29 17:11
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dwadmin", "0002_alter_webixadminmenu_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebixAdminMenuLanguage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=settings.LANGUAGES,
                        max_length=8,
                        verbose_name="Language",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Node name")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dwadmin.webixadminmenu",
                        verbose_name="Menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webix Admin Menu Language",
                "verbose_name_plural": "Webix Admin Menu Languages",
                "unique_together": {("menu", "language")},
            },
        ),
    ]
