# Generated by Django 3.2.4 on 2021-06-21 17:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_webix', '0004_auto_20210120_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='webixadminmenu',
            name='prefix',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Enabled groups'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_webix.webixadminmenu', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='url',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Collegamento web'),
        ),
    ]
