# Generated by Django 3.2.3 on 2021-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_webix', '0005_auto_20210621_1728'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='webixadminmenu',
            managers=[
            ],
        ),
    ]
