# Generated by Django 3.2.6 on 2021-10-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('admin_webix', '0006_alter_webixadminmenu_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webixadminmenu',
            name='active_all',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active for all'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Node name'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='webixadminmenu',
            name='url',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Web link'),
        ),
    ]
