# Generated by Django 2.2.6 on 2019-12-24 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allegato', models.FileField(blank=True, null=True, upload_to='import_file')),
            ],
        ),
    ]
