# Generated by Django 2.2.6 on 2020-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='import_file', verbose_name='Allegato'),
        ),
    ]
