# Generated by Django 2.2.7 on 2020-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_validator', '0002_auto_20200109_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='import_file', verbose_name='Attachment'),
        ),
    ]
