# Generated by Django 3.0.5 on 2020-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_validator', '0003_auto_20200109_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='import_file', verbose_name='Allegato'),
        ),
    ]
