# Generated by Django 3.0.5 on 2020-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_validator', '0004_auto_20200428_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='import_file', verbose_name='Attachment'),
        ),
    ]
