# Generated by Django 3.0.7 on 2020-10-15 12:18

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('django_validator', '0005_auto_20200504_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='allegato',
            field=models.FileField(blank=True, null=True, upload_to='import_file', verbose_name=_('Attachment')),
        ),
    ]
